// ============================================================
// loot.ts — D&D 3.5-based loot tables for random item generation
// ============================================================

export type ItemCategory =
  | "weapon"
  | "armor"
  | "gear"
  | "trade_good"
  | "alchemical"
  | "consumable";

export type LootItem = {
  id: string;
  name: string;
  category: ItemCategory;
  value: number; // gold pieces
  weight: number; // pounds
  description: string; // brief flavor text
  effect?: string; // mechanical effect if any
};

export type LootTier = "junk" | "common" | "uncommon" | "rare" | "legendary";

export type TerrainLoot = {
  terrain: string;
  junk: string[]; // flavor descriptions for junk finds
  minor: string[]; // flavor for minor finds
  major: string[]; // flavor for major finds
};

// ============================================================
//  JUNK LOOT  (0 – 2 gp)
// ============================================================

export const JUNK_LOOT: LootItem[] = [
  {
    id: "junk_broken_dagger",
    name: "Broken Dagger",
    category: "weapon",
    value: 0.5,
    weight: 0.5,
    description: "A snapped blade with a chipped handle. Barely useful as a letter opener.",
  },
  {
    id: "junk_rusty_nails",
    name: "Rusty Nails",
    category: "gear",
    value: 0.1,
    weight: 0.25,
    description: "A handful of bent, corroded nails. Maybe a blacksmith could melt them down.",
  },
  {
    id: "junk_tattered_cloth",
    name: "Tattered Cloth",
    category: "trade_good",
    value: 0.2,
    weight: 0.5,
    description: "A scrap of sun-bleached fabric, frayed at every edge.",
  },
  {
    id: "junk_cracked_pot",
    name: "Cracked Pot",
    category: "gear",
    value: 0.3,
    weight: 2,
    description: "A clay cooking pot with a jagged crack running down the side.",
  },
  {
    id: "junk_bird_feathers",
    name: "Bird Feathers",
    category: "trade_good",
    value: 0.1,
    weight: 0.1,
    description: "A small bundle of dull plumage. Could serve as quill stock in a pinch.",
  },
  {
    id: "junk_old_boot",
    name: "Old Boot",
    category: "gear",
    value: 0.1,
    weight: 1,
    description: "A single worn-out boot. Its partner is long gone.",
  },
  {
    id: "junk_rat_bones",
    name: "Rat Bones",
    category: "trade_good",
    value: 0.1,
    weight: 0.1,
    description: "Tiny bleached bones. Some hedge witches pay copper for these.",
  },
  {
    id: "junk_dull_gemstone",
    name: "Dull Gemstone",
    category: "trade_good",
    value: 1,
    weight: 0.1,
    description: "A cloudy, poorly cut stone. It catches light but not admiration.",
  },
  {
    id: "junk_wooden_button",
    name: "Wooden Button",
    category: "trade_good",
    value: 0.05,
    weight: 0.05,
    description: "A carved wooden button with a faded crest. Off someone's coat, once.",
  },
  {
    id: "junk_stale_bread",
    name: "Stale Bread",
    category: "consumable",
    value: 0.05,
    weight: 0.5,
    description: "Rock-hard bread. Edible if soaked in water for an hour. Maybe.",
  },
  {
    id: "junk_torn_map_fragment",
    name: "Torn Map Fragment",
    category: "gear",
    value: 0.5,
    weight: 0.1,
    description: "A corner of a larger map showing unmarked hills and a partial river.",
  },
  {
    id: "junk_faded_playing_cards",
    name: "Faded Playing Cards",
    category: "gear",
    value: 0.2,
    weight: 0.1,
    description: "A partial deck of cards with water-stained illustrations.",
  },
  {
    id: "junk_copper_ring",
    name: "Copper Ring",
    category: "trade_good",
    value: 0.5,
    weight: 0.05,
    description: "A simple band of tarnished copper. No enchantment, just sentiment.",
  },
  {
    id: "junk_chipped_arrowhead",
    name: "Chipped Arrowhead",
    category: "weapon",
    value: 0.1,
    weight: 0.1,
    description: "A flint arrowhead with a large chip. Useless for hunting.",
  },
  {
    id: "junk_dried_herbs",
    name: "Dried Herbs",
    category: "consumable",
    value: 0.3,
    weight: 0.1,
    description: "A crumbling bundle of unidentifiable dried leaves. Smells vaguely medicinal.",
  },
  {
    id: "junk_bent_spoon",
    name: "Bent Spoon",
    category: "gear",
    value: 0.1,
    weight: 0.25,
    description: "A tin spoon bent almost double. Someone was very angry at their porridge.",
  },
  {
    id: "junk_empty_vial",
    name: "Empty Vial",
    category: "gear",
    value: 0.5,
    weight: 0.1,
    description: "A small glass vial with a cork stopper. Residue inside hints at past contents.",
  },
  {
    id: "junk_charcoal_stick",
    name: "Charcoal Stick",
    category: "gear",
    value: 0.1,
    weight: 0.1,
    description: "A stick of drawing charcoal. Good for marking walls or ruining sleeves.",
  },
  {
    id: "junk_tarnished_buckle",
    name: "Tarnished Buckle",
    category: "trade_good",
    value: 0.3,
    weight: 0.25,
    description: "A belt buckle gone green with age. The design is nearly worn smooth.",
  },
  {
    id: "junk_bone_dice",
    name: "Bone Dice",
    category: "gear",
    value: 0.2,
    weight: 0.1,
    description: "A pair of yellowed bone dice. One is slightly heavier on the six side.",
  },
  // Clothing junk
  {
    id: "junk_worn_sandals",
    name: "Worn Sandals",
    category: "gear",
    value: 0.03,
    weight: 0.5,
    description: "Leather sandals with a snapped strap. One sole is worn through.",
  },
  {
    id: "junk_moth_eaten_scarf",
    name: "Moth-Eaten Scarf",
    category: "gear",
    value: 0.1,
    weight: 0,
    description: "A woolen scarf riddled with holes. Still vaguely warm.",
  },
  {
    id: "junk_stained_tunic",
    name: "Stained Tunic",
    category: "gear",
    value: 0.2,
    weight: 1,
    description: "A rough tunic with unidentifiable stains. Wearable, barely.",
  },
  {
    id: "junk_ragged_cloak",
    name: "Ragged Cloak",
    category: "gear",
    value: 0.3,
    weight: 1,
    description: "A patched wool cloak with a frayed hem. Better than nothing in the rain.",
  },
  {
    id: "junk_cracked_belt",
    name: "Cracked Belt",
    category: "gear",
    value: 0.1,
    weight: 0,
    description: "A dried-out leather belt with a bent buckle.",
  },
  // A&E Guide trade goods — junk tier
  {
    id: "junk_tallow_stub",
    name: "Tallow Candle Stub",
    category: "trade_good",
    value: 0.01,
    weight: 0.1,
    description: "A half-melted tallow candle, still faintly scented with rendered fat.",
  },
  {
    id: "junk_hemp_twine",
    name: "Scrap of Hemp Twine",
    category: "trade_good",
    value: 0.05,
    weight: 0.1,
    description: "A tangled length of rough hemp twine, good for maybe one knot.",
  },
  {
    id: "junk_clay_cup",
    name: "Chipped Clay Cup",
    category: "gear",
    value: 0.03,
    weight: 0.5,
    description: "A handleless clay cup with a chip on the rim. Holds water, barely.",
  },
  {
    id: "junk_wooden_comb",
    name: "Wooden Comb",
    category: "gear",
    value: 0.05,
    weight: 0.1,
    description: "A rough-carved boxwood comb missing several teeth.",
  },
  {
    id: "junk_fishhook",
    name: "Iron Fishhook",
    category: "gear",
    value: 0.1,
    weight: 0.05,
    description: "A bent iron fishhook, barbed but rusty. Still sharp enough to catch a meal.",
  },
  {
    id: "junk_chalk_chunk",
    name: "Chunk of Chalk",
    category: "trade_good",
    value: 0.01,
    weight: 0.25,
    description: "A lump of white chalk. Good for marking walls or drawing rude pictures.",
  },
  {
    id: "junk_grain_sack",
    name: "Sack of Spoiled Grain",
    category: "trade_good",
    value: 0.02,
    weight: 3,
    description: "A small burlap sack of mildewed wheat. The weevils have had their fill.",
  },
  {
    id: "junk_rabbit_pelt",
    name: "Rabbit Pelt",
    category: "trade_good",
    value: 0.03,
    weight: 0.25,
    description: "A small, poorly cured rabbit skin. Stiff and patchy.",
  },
  {
    id: "junk_wax_lump",
    name: "Lump of Beeswax",
    category: "trade_good",
    value: 0.1,
    weight: 0.25,
    description: "A sticky lump of raw beeswax. Useful for waterproofing thread.",
  },
  {
    id: "junk_tar_pot",
    name: "Pot of Dried Tar",
    category: "trade_good",
    value: 0.2,
    weight: 1,
    description: "A small clay pot of hardened pine tar. Could be softened over a fire.",
  },
  {
    id: "junk_rough_soap",
    name: "Rough Soap Bar",
    category: "trade_good",
    value: 0.05,
    weight: 0.25,
    description: "A lump of lye soap, cracked and gritty. It'll strip the dirt off — and half your skin.",
  },
  {
    id: "junk_iron_nail_bag",
    name: "Bag of Iron Nails",
    category: "trade_good",
    value: 0.5,
    weight: 1,
    description: "A canvas pouch of mixed iron nails, some bent, some usable.",
  },
  {
    id: "junk_leather_scrap",
    name: "Leather Scrap",
    category: "trade_good",
    value: 0.1,
    weight: 0.5,
    description: "A palm-sized piece of cured cowhide. Enough for a patch or two.",
  },
  {
    id: "junk_wooden_bowl",
    name: "Wooden Bowl",
    category: "gear",
    value: 0.03,
    weight: 0.5,
    description: "A hand-turned wooden bowl, warped from moisture but still functional.",
  },
  {
    id: "junk_copper_wire",
    name: "Copper Wire",
    category: "trade_good",
    value: 0.5,
    weight: 0.1,
    description: "A coil of thin copper wire, tarnished green. An armorer or jeweler could use it.",
  },
];

// ============================================================
//  COMMON LOOT  (2 – 15 gp)
// ============================================================

export const COMMON_LOOT: LootItem[] = [
  {
    id: "common_dagger",
    name: "Dagger",
    category: "weapon",
    value: 2,
    weight: 1,
    description: "A simple but functional steel dagger.",
    effect: "1d4 piercing, 19-20/x2 crit, 10 ft range increment",
  },
  {
    id: "common_short_sword",
    name: "Short Sword",
    category: "weapon",
    value: 10,
    weight: 2,
    description: "A well-balanced blade favored by scouts and rogues.",
    effect: "1d6 piercing, 19-20/x2 crit",
  },
  {
    id: "common_sturdy_club",
    name: "Sturdy Club",
    category: "weapon",
    value: 3,
    weight: 3,
    description: "A heavy oaken club reinforced with iron bands.",
    effect: "1d6 bludgeoning, x2 crit",
  },
  {
    id: "common_leather_sling",
    name: "Leather Sling",
    category: "weapon",
    value: 2,
    weight: 0.5,
    description: "A sling of supple leather with a braided cord.",
    effect: "1d4 bludgeoning, x2 crit, 50 ft range increment",
  },
  {
    id: "common_quality_torches",
    name: "Quality Torches (3)",
    category: "gear",
    value: 2,
    weight: 3,
    description: "Three pitch-soaked torches that burn bright and long.",
    effect: "20 ft bright light, 40 ft shadowy; burns 1 hour each",
  },
  {
    id: "common_silk_rope",
    name: "Silk Rope (50 ft)",
    category: "gear",
    value: 10,
    weight: 5,
    description: "Smooth yet strong rope woven from spider silk and flax.",
    effect: "HP 4, Break DC 24, +2 to Use Rope checks",
  },
  {
    id: "common_rations_5day",
    name: "Rations (5 days)",
    category: "consumable",
    value: 2.5,
    weight: 5,
    description: "Jerky, hardtack, and dried fruit wrapped in oilcloth.",
  },
  {
    id: "common_waterskin",
    name: "Waterskin",
    category: "gear",
    value: 1,
    weight: 4,
    description: "A leather waterskin filled with clean water. Holds a day's worth.",
  },
  {
    id: "common_healers_kit",
    name: "Healer's Kit",
    category: "gear",
    value: 5,
    weight: 1,
    description: "A leather pouch of bandages, salves, and splinting rods.",
    effect: "+2 to Heal checks, 5 uses remaining",
  },
  {
    id: "common_trail_rations_pack",
    name: "Trail Rations Pack",
    category: "consumable",
    value: 3,
    weight: 8,
    description: "A traveler's pack of smoked meats, nuts, and honeycomb.",
  },
  {
    id: "common_silver_ring",
    name: "Silver Ring",
    category: "trade_good",
    value: 3,
    weight: 0.05,
    description: "A thin band of polished silver. Simple but genuine.",
  },
  {
    id: "common_padded_armor",
    name: "Padded Armor",
    category: "armor",
    value: 5,
    weight: 10,
    description: "Layers of quilted cloth and cotton batting.",
    effect: "+1 AC, max Dex +8, armor check penalty 0",
  },
  {
    id: "common_leather_armor",
    name: "Leather Armor",
    category: "armor",
    value: 10,
    weight: 15,
    description: "Boiled and hardened leather shaped into a vest and bracers.",
    effect: "+2 AC, max Dex +6, armor check penalty 0",
  },
  {
    id: "common_light_wooden_shield",
    name: "Light Wooden Shield",
    category: "armor",
    value: 3,
    weight: 5,
    description: "A round shield of layered wood banded with iron.",
    effect: "+1 AC, armor check penalty -1",
  },
  {
    id: "common_backpack",
    name: "Backpack",
    category: "gear",
    value: 2,
    weight: 2,
    description: "A sturdy canvas pack with leather straps and brass fittings.",
  },
  {
    id: "common_bedroll",
    name: "Bedroll",
    category: "gear",
    value: 1,
    weight: 5,
    description: "A wool-stuffed bedroll that keeps the cold ground at bay.",
  },
  {
    id: "common_flint_and_steel",
    name: "Flint and Steel",
    category: "gear",
    value: 1,
    weight: 0.5,
    description: "A fire-starting kit in a small tin case.",
    effect: "Start a fire as a full-round action",
  },
  {
    id: "common_mess_kit",
    name: "Mess Kit",
    category: "gear",
    value: 1,
    weight: 1,
    description: "A compact set of tin plate, cup, fork, and folding knife.",
  },
  {
    id: "common_travelers_outfit",
    name: "Traveler's Outfit",
    category: "gear",
    value: 1,
    weight: 5,
    description: "Sturdy boots, wool trousers, a linen shirt, and a cloak.",
  },
  {
    id: "common_peasant_outfit",
    name: "Peasant's Outfit",
    category: "gear",
    value: 0.1,
    weight: 2,
    description: "A loose shirt, breeches, and cloth shoes. Rough but serviceable.",
  },
  {
    id: "common_artisan_outfit",
    name: "Artisan's Outfit",
    category: "gear",
    value: 1,
    weight: 4,
    description: "Sturdy work clothes with tool loops and a leather apron.",
  },
  {
    id: "common_wool_cloak",
    name: "Wool Cloak",
    category: "gear",
    value: 0.5,
    weight: 1,
    description: "A plain brown cloak with a bone clasp. Keeps the rain off.",
  },
  {
    id: "common_leather_boots",
    name: "Leather Boots",
    category: "gear",
    value: 1,
    weight: 1,
    description: "Sturdy calf-high leather boots. Well-worn but sound.",
  },
  {
    id: "common_leather_gloves",
    name: "Leather Gloves",
    category: "gear",
    value: 1,
    weight: 0,
    description: "Fitted work gloves. Protects hands from rope burn and brambles.",
  },
  {
    id: "common_wide_hat",
    name: "Wide-Brimmed Hat",
    category: "gear",
    value: 0.5,
    weight: 0.5,
    description: "A broad felt hat that shades the face from sun and rain.",
  },
  {
    id: "common_leather_belt",
    name: "Leather Belt",
    category: "gear",
    value: 0.5,
    weight: 0,
    description: "A sturdy belt with iron buckle. Room for a scabbard and pouches.",
  },
  {
    id: "common_woolen_tunic",
    name: "Woolen Tunic",
    category: "gear",
    value: 0.8,
    weight: 1,
    description: "A knee-length tunic of undyed wool. Common daily wear.",
  },
  {
    id: "common_leather_jerkin",
    name: "Leather Jerkin",
    category: "gear",
    value: 0.5,
    weight: 1,
    description: "A tough sleeveless jerkin worn over lighter clothes.",
  },
  {
    id: "common_handaxe",
    name: "Handaxe",
    category: "weapon",
    value: 6,
    weight: 3,
    description: "A short-hafted axe useful for chopping wood or foes.",
    effect: "1d6 slashing, x3 crit, 10 ft range increment",
  },
  {
    id: "common_javelin",
    name: "Javelin",
    category: "weapon",
    value: 1,
    weight: 2,
    description: "A balanced throwing spear with a fire-hardened tip.",
    effect: "1d6 piercing, x2 crit, 30 ft range increment",
  },
  {
    id: "common_ironwood_staff",
    name: "Ironwood Staff",
    category: "weapon",
    value: 5,
    weight: 4,
    description: "A dark-grained staff, hard as iron but light as ash.",
    effect: "1d6/1d6 bludgeoning (double weapon), x2 crit",
  },
  {
    id: "common_mace",
    name: "Mace",
    category: "weapon",
    value: 12,
    weight: 8,
    description: "A flanged steel mace that delivers crushing blows.",
    effect: "1d8 bludgeoning, x2 crit",
  },
  {
    id: "common_spear",
    name: "Spear",
    category: "weapon",
    value: 2,
    weight: 6,
    description: "A simple spear with an iron point. Versatile and cheap.",
    effect: "1d8 piercing (two-handed), x3 crit, 20 ft range increment",
  },
  {
    id: "common_light_crossbow",
    name: "Light Crossbow",
    category: "weapon",
    value: 12,
    weight: 4,
    description: "A compact crossbow with a quiver of 20 bolts.",
    effect: "1d8 piercing, 19-20/x2 crit, 80 ft range increment",
  },
  {
    id: "common_caltrops",
    name: "Caltrops",
    category: "gear",
    value: 1,
    weight: 2,
    description: "A bag of four-pronged iron spikes to scatter on the ground.",
    effect: "Covers 5 ft square; DC 15 Reflex or 1 damage and half speed",
  },
  {
    id: "common_grappling_hook",
    name: "Grappling Hook",
    category: "gear",
    value: 1,
    weight: 4,
    description: "A three-pronged iron hook for scaling walls.",
    effect: "DC 10 Use Rope to secure; +2 to Climb with rope",
  },
  {
    id: "common_signal_whistle",
    name: "Signal Whistle",
    category: "gear",
    value: 1,
    weight: 0.1,
    description: "A shrill tin whistle audible up to a quarter mile.",
  },
  {
    id: "common_candles_10",
    name: "Candles (10)",
    category: "gear",
    value: 1,
    weight: 1,
    description: "Ten tallow candles wrapped in waxed paper.",
    effect: "5 ft dim light each, burns 1 hour",
  },
  {
    id: "common_flask_of_oil_5",
    name: "Flasks of Oil (5)",
    category: "gear",
    value: 2,
    weight: 5,
    description: "Five clay flasks of lamp oil. Also useful as improvised fire weapons.",
    effect: "Fuel for lantern (6 hrs each) or splash weapon (1d3 fire)",
  },
  // A&E Guide trade goods — common tier
  {
    id: "common_iron_bar",
    name: "Iron Bar",
    category: "trade_good",
    value: 1,
    weight: 10,
    description: "A rough-smelted bar of pig iron. Raw material for any blacksmith.",
  },
  {
    id: "common_copper_ingot",
    name: "Copper Ingot",
    category: "trade_good",
    value: 5,
    weight: 10,
    description: "A half-pound ingot of smelted copper, stamped with a foundry mark.",
  },
  {
    id: "common_sack_of_salt",
    name: "Sack of Salt",
    category: "trade_good",
    value: 5,
    weight: 5,
    description: "A pound of coarse rock salt. Essential for preserving meat on long journeys.",
  },
  {
    id: "common_sack_of_flour",
    name: "Sack of Flour",
    category: "trade_good",
    value: 2,
    weight: 10,
    description: "Ten pounds of milled wheat flour in a canvas sack.",
  },
  {
    id: "common_pepper_pouch",
    name: "Pouch of Pepper",
    category: "trade_good",
    value: 2,
    weight: 0.25,
    description: "A small leather pouch of cracked black peppercorns. Worth its weight to a cook.",
  },
  {
    id: "common_cinnamon_sticks",
    name: "Bundle of Cinnamon",
    category: "trade_good",
    value: 1,
    weight: 0.25,
    description: "A bundle of dried cinnamon bark, tied with string. Aromatic and tradeable.",
  },
  {
    id: "common_wool_bolt",
    name: "Bolt of Rough Wool",
    category: "trade_good",
    value: 1,
    weight: 5,
    description: "A roll of undyed sheep's wool fabric. Standard clothing material.",
  },
  {
    id: "common_linen_bolt",
    name: "Bolt of Linen",
    category: "trade_good",
    value: 3,
    weight: 4,
    description: "A roll of bleached linen cloth, neatly folded and tied.",
  },
  {
    id: "common_fox_pelt",
    name: "Fox Pelt",
    category: "trade_good",
    value: 5,
    weight: 1,
    description: "A red fox skin, well-cured with the brush still attached.",
  },
  {
    id: "common_canvas_yard",
    name: "Canvas (5 sq yards)",
    category: "trade_good",
    value: 2,
    weight: 5,
    description: "Five square yards of heavy canvas. Useful for tarps, sail repair, or shelter.",
  },
  {
    id: "common_iron_cooking_pot",
    name: "Iron Cooking Pot",
    category: "gear",
    value: 5,
    weight: 10,
    description: "A heavy cast-iron pot with a bail handle. Worth its weight on the trail.",
  },
  {
    id: "common_iron_skillet",
    name: "Iron Skillet",
    category: "gear",
    value: 3,
    weight: 4,
    description: "A well-seasoned iron skillet. Trail cooking at its finest.",
  },
  {
    id: "common_crowbar",
    name: "Crowbar",
    category: "gear",
    value: 2,
    weight: 5,
    description: "A bent iron bar for prying open crates, doors, and other stubborn things.",
    effect: "+2 circumstance bonus to Strength checks to force open doors/lids",
  },
  {
    id: "common_fishing_net",
    name: "Fishing Net",
    category: "gear",
    value: 4,
    weight: 5,
    description: "A weighted throw-net of knotted cord, sized for stream fishing.",
  },
  {
    id: "common_pitons_10",
    name: "Pitons (10)",
    category: "gear",
    value: 1,
    weight: 5,
    description: "Ten iron spikes for hammering into rock or wood.",
  },
  {
    id: "common_hooded_lantern",
    name: "Hooded Lantern",
    category: "gear",
    value: 7,
    weight: 2,
    description: "A tin lantern with shutters that can narrow or block its beam.",
    effect: "30 ft bright light, 60 ft shadowy; burns 6 hours per pint of oil",
  },
  {
    id: "common_miners_pick",
    name: "Miner's Pick",
    category: "gear",
    value: 3,
    weight: 10,
    description: "A heavy pick for breaking stone. Not designed as a weapon, but in a pinch...",
    effect: "Improvised weapon: 1d6 piercing, x4 crit, -4 to attack (non-proficient)",
  },
  {
    id: "common_hemp_rope",
    name: "Hemp Rope (50 ft)",
    category: "gear",
    value: 1,
    weight: 10,
    description: "Fifty feet of coarse hemp rope. Rough on the hands but strong.",
    effect: "HP 2, Break DC 23",
  },
  {
    id: "common_belt_pouch",
    name: "Belt Pouch (leather)",
    category: "gear",
    value: 1,
    weight: 0.5,
    description: "A leather belt pouch with a drawstring and bone toggle.",
  },
  {
    id: "common_barrel_empty",
    name: "Empty Barrel",
    category: "gear",
    value: 2,
    weight: 30,
    description: "An oak barrel with iron hoops. Holds 50 gallons or 300 lbs of dry goods.",
  },
  {
    id: "common_wool_blanket",
    name: "Wool Blanket",
    category: "gear",
    value: 1,
    weight: 3,
    description: "A thick undyed wool blanket. Scratchy but warm.",
  },
  {
    id: "common_whetstone",
    name: "Whetstone",
    category: "gear",
    value: 0.5,
    weight: 1,
    description: "A fine-grained stone for keeping blades sharp.",
  },
  {
    id: "common_ink_vial",
    name: "Ink Vial",
    category: "gear",
    value: 8,
    weight: 0.1,
    description: "A small glass vial of iron-gall ink. Writes dark and permanent.",
  },
  {
    id: "common_parchment_5",
    name: "Parchment (5 sheets)",
    category: "gear",
    value: 1,
    weight: 0.1,
    description: "Five sheets of prepared calfskin vellum, smooth and ready for writing.",
  },
  {
    id: "common_tallow_candles_20",
    name: "Tallow Candles (20)",
    category: "trade_good",
    value: 1,
    weight: 2,
    description: "Twenty dipped tallow candles bundled in waxed paper.",
  },
  {
    id: "common_chicken",
    name: "Live Chicken",
    category: "trade_good",
    value: 0.02,
    weight: 3,
    description: "A plump hen. Lays eggs if you keep her fed, or provides one good meal.",
  },
  {
    id: "common_pig",
    name: "Small Pig",
    category: "trade_good",
    value: 3,
    weight: 50,
    description: "A young shoat, fattening up nicely. Worth more alive than butchered.",
  },
  {
    id: "common_scroll_case",
    name: "Scroll Case",
    category: "gear",
    value: 1,
    weight: 0.5,
    description: "A capped leather tube for carrying maps or scrolls. Waterproof.",
  },
  {
    id: "common_merchants_scale",
    name: "Merchant's Scale",
    category: "gear",
    value: 2,
    weight: 1,
    description: "A small hand-held balance scale with brass weights. Standard trade equipment.",
  },
];

// ============================================================
//  UNCOMMON LOOT  (15 – 50 gp)
// ============================================================

export const UNCOMMON_LOOT: LootItem[] = [
  // Clothing (uncommon tier — nicer garments)
  {
    id: "uncommon_entertainer_outfit",
    name: "Entertainer's Outfit",
    category: "gear",
    value: 3,
    weight: 4,
    description: "Flashy garments in bright colors with ribbon trim and brass buttons.",
  },
  {
    id: "uncommon_explorer_outfit",
    name: "Explorer's Outfit",
    category: "gear",
    value: 10,
    weight: 8,
    description: "Reinforced clothing with many pockets, a wide hat, and high boots.",
  },
  {
    id: "uncommon_winter_cloak",
    name: "Winter Cloak",
    category: "gear",
    value: 5,
    weight: 3,
    description: "A heavy cloak lined with wolf fur. Warm as a hearth.",
  },
  {
    id: "uncommon_cold_weather_outfit",
    name: "Cold Weather Outfit",
    category: "gear",
    value: 8,
    weight: 7,
    description: "Wool coat, heavy cloak, fur-lined gloves and boots. Built for bitter cold.",
  },
  {
    id: "uncommon_scholar_outfit",
    name: "Scholar's Outfit",
    category: "gear",
    value: 5,
    weight: 6,
    description: "A long robe over fine linen, with ink-stained cuffs and deep pockets.",
  },
  {
    id: "uncommon_riding_boots",
    name: "Riding Boots",
    category: "gear",
    value: 3,
    weight: 3,
    description: "Tall leather boots with a hard heel for stirrups and a polished finish.",
  },
  {
    id: "uncommon_surcoat",
    name: "Surcoat",
    category: "gear",
    value: 3,
    weight: 3,
    description: "A sleeveless overgarment in dyed linen, suitable for wearing a coat of arms.",
  },
  {
    id: "uncommon_courtier_outfit",
    name: "Courtier's Outfit",
    category: "gear",
    value: 30,
    weight: 6,
    description: "Tailored clothing in fine fabric, suitable for audiences with nobility.",
  },
  {
    id: "uncommon_monks_outfit",
    name: "Monk's Outfit",
    category: "gear",
    value: 5,
    weight: 2,
    description: "A simple, functional garment that allows full freedom of movement.",
  },
  {
    id: "uncommon_cleric_vestments",
    name: "Cleric's Vestments",
    category: "gear",
    value: 5,
    weight: 6,
    description: "Ceremonial robes embroidered with holy symbols.",
  },
  {
    id: "uncommon_longsword",
    name: "Longsword",
    category: "weapon",
    value: 15,
    weight: 4,
    description: "A straight-bladed sword of good steel with a leather-wrapped grip.",
    effect: "1d8 slashing, 19-20/x2 crit",
  },
  {
    id: "uncommon_fine_battleaxe",
    name: "Fine Battleaxe",
    category: "weapon",
    value: 20,
    weight: 6,
    description: "A broad-bladed axe with rune-etched cheeks and a hickory haft.",
    effect: "1d8 slashing, x3 crit",
  },
  {
    id: "uncommon_dwarven_warhammer",
    name: "Dwarven Warhammer",
    category: "weapon",
    value: 25,
    weight: 5,
    description: "A compact warhammer stamped with a dwarven forge-mark.",
    effect: "1d8 bludgeoning, x3 crit",
  },
  {
    id: "uncommon_shortbow",
    name: "Shortbow",
    category: "weapon",
    value: 30,
    weight: 2,
    description: "A recurve bow of yew and sinew, compact enough for mounted use.",
    effect: "1d6 piercing, x3 crit, 60 ft range increment",
  },
  {
    id: "uncommon_battered_chain_shirt",
    name: "Battered Chain Shirt",
    category: "armor",
    value: 30,
    weight: 25,
    description: "A chain shirt missing a few links but still serviceable.",
    effect: "+4 AC, max Dex +4, armor check penalty -2",
  },
  {
    id: "uncommon_scale_mail",
    name: "Scale Mail",
    category: "armor",
    value: 50,
    weight: 30,
    description: "Overlapping steel scales riveted to a leather backing.",
    effect: "+4 AC, max Dex +3, armor check penalty -4",
  },
  {
    id: "uncommon_studded_leather",
    name: "Studded Leather",
    category: "armor",
    value: 25,
    weight: 20,
    description: "Leather armor reinforced with rows of metal studs.",
    effect: "+3 AC, max Dex +5, armor check penalty -1",
  },
  {
    id: "uncommon_heavy_steel_shield",
    name: "Heavy Steel Shield",
    category: "armor",
    value: 20,
    weight: 15,
    description: "A broad steel shield emblazoned with a faded heraldic device.",
    effect: "+2 AC, armor check penalty -2",
  },
  {
    id: "uncommon_silver_dagger",
    name: "Silver Dagger",
    category: "weapon",
    value: 22,
    weight: 1,
    description: "An alchemical silver dagger that gleams with a pale sheen.",
    effect: "1d4 piercing, 19-20/x2 crit; bypasses lycanthrope DR",
  },
  {
    id: "uncommon_masterwork_arrows",
    name: "Masterwork Arrows (20)",
    category: "weapon",
    value: 26,
    weight: 3,
    description: "Twenty precisely fletched arrows in a waxed quiver.",
    effect: "+1 to attack rolls (masterwork)",
  },
  {
    id: "uncommon_copper_bracelet",
    name: "Copper Bracelet",
    category: "trade_good",
    value: 15,
    weight: 0.25,
    description: "A hammered copper bracelet set with tiny turquoise beads.",
  },
  {
    id: "uncommon_silver_pendant",
    name: "Silver Pendant",
    category: "trade_good",
    value: 25,
    weight: 0.1,
    description: "A silver pendant on a fine chain, shaped like a crescent moon.",
  },
  {
    id: "uncommon_small_ruby",
    name: "Small Ruby",
    category: "trade_good",
    value: 50,
    weight: 0.05,
    description: "A deep crimson gemstone, roughly cut but vivid in color.",
  },
  {
    id: "uncommon_jade_figurine",
    name: "Jade Figurine",
    category: "trade_good",
    value: 25,
    weight: 0.5,
    description: "A tiny jade carving of a coiled serpent, smooth with age.",
  },
  {
    id: "uncommon_bolt_of_fine_cloth",
    name: "Bolt of Fine Cloth",
    category: "trade_good",
    value: 20,
    weight: 5,
    description: "A roll of richly dyed linen, worth good coin to a tailor.",
  },
  {
    id: "uncommon_elven_mead",
    name: "Bottle of Elven Mead",
    category: "consumable",
    value: 15,
    weight: 1.5,
    description: "A pale golden mead that smells of wildflowers and honey.",
  },
  {
    id: "uncommon_exotic_spice",
    name: "Jar of Exotic Spice",
    category: "trade_good",
    value: 20,
    weight: 0.5,
    description: "A sealed clay jar of saffron and cardamom from distant lands.",
  },
  {
    id: "uncommon_bladefire_flask",
    name: "Bladefire Flask",
    category: "alchemical",
    value: 20,
    weight: 0.5,
    description: "An orange paste that ignites when spread on a weapon's edge.",
    effect: "Apply to weapon as a standard action; +1 fire damage for 1d6 rounds",
  },
  {
    id: "uncommon_ghostoil_flask",
    name: "Ghostoil Flask",
    category: "alchemical",
    value: 50,
    weight: 0.5,
    description: "A translucent oil that shimmers with faint spectral light.",
    effect: "Apply to weapon; can strike incorporeal creatures for 2 rounds",
  },
  {
    id: "uncommon_verminbane_flask",
    name: "Verminbane Flask",
    category: "alchemical",
    value: 20,
    weight: 0.5,
    description: "A pungent alchemical mixture that repels insects and vermin.",
    effect: "Vermin must succeed DC 15 Will save to approach within 5 ft for 1 hour",
  },
  {
    id: "uncommon_alchemists_fire",
    name: "Alchemist's Fire",
    category: "alchemical",
    value: 20,
    weight: 1,
    description: "A flask of sticky, volatile liquid that ignites on contact with air.",
    effect: "Ranged touch attack; 1d6 fire damage, then 1d6 fire next round",
  },
  {
    id: "uncommon_silk_hammock",
    name: "Silk Hammock",
    category: "gear",
    value: 15,
    weight: 2,
    description: "A lightweight hammock of woven silk. Packs down to fist-size.",
  },
  {
    id: "uncommon_silent_shoes",
    name: "Silent Shoes",
    category: "gear",
    value: 20,
    weight: 1,
    description: "Soft-soled shoes crafted for stealth, with padded heels.",
    effect: "+2 circumstance bonus to Move Silently checks",
  },
  {
    id: "uncommon_thieves_tools",
    name: "Thieves' Tools",
    category: "gear",
    value: 30,
    weight: 1,
    description: "A leather roll of lockpicks, tension wrenches, and slim probes.",
    effect: "Required for Open Lock checks; no penalty",
  },
  {
    id: "uncommon_climbers_kit",
    name: "Climber's Kit",
    category: "gear",
    value: 50,
    weight: 5,
    description: "Pitons, crampons, carabiners, and 50 ft of knotted rope.",
    effect: "+2 circumstance bonus to Climb checks",
  },
  {
    id: "uncommon_healers_kit_full",
    name: "Healer's Kit (full)",
    category: "gear",
    value: 50,
    weight: 1,
    description: "A complete healer's kit with fresh bandages and potent salves.",
    effect: "+2 to Heal checks, 10 uses",
  },
  {
    id: "uncommon_magnifying_glass",
    name: "Magnifying Glass",
    category: "gear",
    value: 50,
    weight: 0.5,
    description: "A polished crystal lens in a brass frame. Useful for studying fine detail.",
    effect: "+2 to Appraise checks for detailed items; can start fire in bright sun",
  },
  {
    id: "uncommon_holy_water_2",
    name: "Holy Water (2 flasks)",
    category: "alchemical",
    value: 50,
    weight: 2,
    description: "Two crystal flasks of water blessed by a temple cleric.",
    effect: "2d4 damage to undead/evil outsiders on direct hit; 1 splash",
  },
  // A&E Guide trade goods — uncommon tier
  {
    id: "uncommon_saffron_jar",
    name: "Jar of Saffron",
    category: "trade_good",
    value: 15,
    weight: 0.25,
    description: "A sealed clay jar of dried saffron threads. Worth a small fortune by weight.",
  },
  {
    id: "uncommon_indigo_cake",
    name: "Cake of Indigo Dye",
    category: "trade_good",
    value: 15,
    weight: 1,
    description: "A dense block of pressed indigo, deep blue and crumbly. Dyers pay well.",
  },
  {
    id: "uncommon_mink_pelt",
    name: "Mink Pelt",
    category: "trade_good",
    value: 20,
    weight: 0.5,
    description: "A glossy mink skin, supple and well-preserved. Popular with furriers.",
  },
  {
    id: "uncommon_ermine_pelt",
    name: "Ermine Pelt",
    category: "trade_good",
    value: 30,
    weight: 0.25,
    description: "A small white ermine skin with a black-tipped tail. Symbol of nobility.",
  },
  {
    id: "uncommon_cask_of_brandy",
    name: "Cask of Brandy",
    category: "trade_good",
    value: 20,
    weight: 25,
    description: "A small oak cask of apple brandy, well-aged and smooth.",
  },
  {
    id: "uncommon_vanilla_bundle",
    name: "Bundle of Vanilla Pods",
    category: "trade_good",
    value: 15,
    weight: 0.25,
    description: "A dozen cured vanilla pods from southern shores. Rare and fragrant.",
  },
  {
    id: "uncommon_cochineal_pouch",
    name: "Pouch of Cochineal",
    category: "trade_good",
    value: 20,
    weight: 0.5,
    description: "Dried cochineal insects used to make vivid crimson dye. Very tradeable.",
  },
  {
    id: "uncommon_silver_candlestick",
    name: "Silver Candlestick",
    category: "trade_good",
    value: 25,
    weight: 2,
    description: "A polished silver candlestick with a weighted base. Fine dining ware.",
  },
  {
    id: "uncommon_silver_mirror",
    name: "Small Silver Mirror",
    category: "gear",
    value: 35,
    weight: 0.5,
    description: "A hand mirror of polished silver in a carved wooden frame.",
  },
  {
    id: "uncommon_masterwork_tools",
    name: "Masterwork Artisan's Tools",
    category: "gear",
    value: 50,
    weight: 5,
    description: "A complete set of finely made craft tools in a fitted leather case.",
    effect: "+2 circumstance bonus to relevant Craft checks",
  },
  {
    id: "uncommon_four_person_tent",
    name: "Tent (4-person)",
    category: "gear",
    value: 15,
    weight: 20,
    description: "A canvas tent with poles, stakes, and guy lines. Sleeps four uncomfortably.",
  },
  {
    id: "uncommon_riding_saddle",
    name: "Riding Saddle",
    category: "gear",
    value: 25,
    weight: 25,
    description: "A leather riding saddle with stirrups and cinch. Standard military issue.",
  },
  {
    id: "uncommon_silver_holy_symbol",
    name: "Silver Holy Symbol",
    category: "gear",
    value: 25,
    weight: 1,
    description: "A holy symbol cast in solid silver, stamped with a deity's seal.",
    effect: "Divine focus for spellcasting",
  },
  {
    id: "uncommon_lute",
    name: "Lute",
    category: "gear",
    value: 35,
    weight: 3,
    description: "A pear-shaped lute with gut strings and a rosewood soundboard.",
    effect: "Required for Perform (string instruments) checks",
  },
  {
    id: "uncommon_flute",
    name: "Silver Flute",
    category: "gear",
    value: 20,
    weight: 0.5,
    description: "A slender flute of polished silver. Warm, clear tone.",
    effect: "Required for Perform (wind instruments) checks",
  },
  {
    id: "uncommon_cow",
    name: "Dairy Cow",
    category: "trade_good",
    value: 10,
    weight: 0,
    description: "A healthy milking cow. Produces a gallon of milk per day.",
  },
  {
    id: "uncommon_ox",
    name: "Draft Ox",
    category: "trade_good",
    value: 15,
    weight: 0,
    description: "A strong, docile ox trained to pull carts and plows.",
  },
  {
    id: "uncommon_donkey",
    name: "Donkey",
    category: "trade_good",
    value: 8,
    weight: 0,
    description: "A sturdy pack donkey. Carries 100 lbs without complaint.",
  },
  {
    id: "uncommon_disguise_kit",
    name: "Disguise Kit",
    category: "gear",
    value: 50,
    weight: 8,
    description: "Makeup, wigs, prosthetics, and adhesives in a locked case.",
    effect: "+2 circumstance bonus to Disguise checks; 10 uses",
  },
  {
    id: "uncommon_bullseye_lantern",
    name: "Bullseye Lantern",
    category: "gear",
    value: 12,
    weight: 3,
    description: "A lantern with a polished reflector that focuses light in a 60-ft cone.",
    effect: "60 ft bright cone, 120 ft shadowy; burns 6 hours per pint of oil",
  },
  {
    id: "uncommon_iron_manacles",
    name: "Iron Manacles",
    category: "gear",
    value: 15,
    weight: 2,
    description: "A pair of heavy iron wrist shackles with a key.",
    effect: "Break DC 26, Escape Artist DC 30",
  },
  {
    id: "uncommon_chess_set",
    name: "Carved Chess Set",
    category: "trade_good",
    value: 25,
    weight: 3,
    description: "A wooden chess set with bone-inlaid pieces. Popular tavern entertainment.",
  },
];

// ============================================================
//  RARE LOOT  (50 – 150 gp)
// ============================================================

export const RARE_LOOT: LootItem[] = [
  // High-value clothing
  {
    id: "rare_noble_outfit",
    name: "Noble's Outfit",
    category: "gear",
    value: 75,
    weight: 10,
    description: "Silk shirt, velvet doublet, fur-trimmed cloak, and jeweled accessories.",
  },
  {
    id: "rare_royal_outfit",
    name: "Royal Outfit",
    category: "gear",
    value: 200,
    weight: 15,
    description: "Ermine-trimmed robes and cloth-of-gold. Fit for a king.",
  },
  {
    id: "rare_fine_steel_longsword",
    name: "Fine Steel Longsword",
    category: "weapon",
    value: 65,
    weight: 4,
    description: "An expertly forged longsword with a mirror-bright blade and wire-wrapped hilt.",
    effect: "1d8 slashing, 19-20/x2 crit; -1 armor check penalty (quality)",
  },
  {
    id: "rare_exceptional_dagger",
    name: "Exceptional Dagger",
    category: "weapon",
    value: 55,
    weight: 1,
    description: "A leaf-shaped dagger of layered steel, balanced perfectly for throwing.",
    effect: "1d4 piercing, 19-20/x2 crit, 10 ft range; +1 attack (masterwork quality)",
  },
  {
    id: "rare_dented_breastplate",
    name: "Dented Breastplate",
    category: "armor",
    value: 75,
    weight: 30,
    description: "A steel breastplate bearing the dents of past battles. Still protects well.",
    effect: "+5 AC, max Dex +3, armor check penalty -4",
  },
  {
    id: "rare_silvered_chain_links",
    name: "Silvered Chain Links",
    category: "armor",
    value: 80,
    weight: 12,
    description: "A vest of interlocking silver-washed rings, light and faintly luminous.",
    effect: "+4 AC, max Dex +5, armor check penalty -1; silver sheen",
  },
  {
    id: "rare_gold_ring",
    name: "Gold Ring",
    category: "trade_good",
    value: 50,
    weight: 0.05,
    description: "A plain gold band, heavy for its size. Worth its weight at any jeweler.",
  },
  {
    id: "rare_gold_necklace",
    name: "Gold Necklace",
    category: "trade_good",
    value: 100,
    weight: 0.25,
    description: "A rope-chain necklace of bright gold with an intricate clasp.",
  },
  {
    id: "rare_polished_gemstone",
    name: "Polished Gemstone",
    category: "trade_good",
    value: 75,
    weight: 0.05,
    description: "A faceted green peridot that catches the light beautifully.",
  },
  {
    id: "rare_topaz",
    name: "Topaz",
    category: "trade_good",
    value: 100,
    weight: 0.05,
    description: "A brilliant amber-gold topaz, properly cut and ready for setting.",
  },
  {
    id: "rare_pearl",
    name: "Pearl",
    category: "trade_good",
    value: 100,
    weight: 0.05,
    description: "A lustrous white pearl with a subtle pink iridescence.",
  },
  {
    id: "rare_silver_goblet",
    name: "Silver Goblet",
    category: "trade_good",
    value: 60,
    weight: 1,
    description: "A finely wrought silver goblet with grape-leaf engravings.",
  },
  {
    id: "rare_ornate_dagger",
    name: "Ornate Dagger",
    category: "weapon",
    value: 80,
    weight: 1,
    description: "A ceremonial dagger with a jeweled pommel and etched blade.",
    effect: "1d4 piercing, 19-20/x2 crit; double value as art object",
  },
  {
    id: "rare_bolt_of_silk",
    name: "Bolt of Silk",
    category: "trade_good",
    value: 100,
    weight: 5,
    description: "A bolt of shimmering silk in deep violet. A noble's fabric.",
  },
  {
    id: "rare_rare_perfume",
    name: "Rare Perfume",
    category: "trade_good",
    value: 75,
    weight: 0.5,
    description: "A crystal vial of perfume distilled from night-blooming jasmine.",
  },
  {
    id: "rare_antique_brooch",
    name: "Antique Brooch",
    category: "trade_good",
    value: 80,
    weight: 0.1,
    description: "A filigree brooch of old elven make, set with a tiny opal.",
  },
  {
    id: "rare_restful_candle",
    name: "Restful Candle",
    category: "alchemical",
    value: 100,
    weight: 0.5,
    description: "A beeswax candle infused with lavender and dreamleaf extract.",
    effect: "Burn during rest; double natural healing for the night",
  },
  {
    id: "rare_focusing_candle",
    name: "Focusing Candle",
    category: "alchemical",
    value: 100,
    weight: 0.5,
    description: "A pale candle that burns with a steady, trance-inducing flame.",
    effect: "Burn during study; +1 alchemical bonus to Knowledge checks for 4 hours",
  },
  {
    id: "rare_clearbreath_vial",
    name: "Clearbreath Vial",
    category: "alchemical",
    value: 50,
    weight: 0.25,
    description: "A sharp-smelling tincture that clears the sinuses instantly.",
    effect: "+4 alchemical bonus to Fortitude saves vs stench and inhaled effects for 1 hour",
  },
  {
    id: "rare_dwarfblind_stone",
    name: "Dwarfblind Stone",
    category: "alchemical",
    value: 50,
    weight: 0.5,
    description: "A fist-sized chalite stone that emits a soft white glow when crushed.",
    effect: "Negates darkvision in 20 ft radius for 10 minutes",
  },
  {
    id: "rare_fleetfoot_vial",
    name: "Fleetfoot Vial",
    category: "alchemical",
    value: 50,
    weight: 0.25,
    description: "A fizzy amber liquid that makes the legs tingle with energy.",
    effect: "Run at x5 speed (instead of x4) for 1 minute",
  },
  {
    id: "rare_vicious_bleeder",
    name: "Vicious Bleeder",
    category: "alchemical",
    value: 50,
    weight: 0.5,
    description: "A dark red paste applied to a blade's edge that prevents clotting.",
    effect: "Apply to weapon; wounded target bleeds 1 hp/round for 2 extra rounds",
  },
  {
    id: "rare_potion_of_healing",
    name: "Small Potion of Healing",
    category: "consumable",
    value: 50,
    weight: 0.5,
    description: "A red potion in a glass vial sealed with wax. Warm to the touch.",
    effect: "Heals 1d8+1 hit points when consumed",
  },
  {
    id: "rare_elven_rope",
    name: "Elven Rope (20 ft)",
    category: "gear",
    value: 50,
    weight: 1,
    description: "Thin silvery rope of elven make, incredibly strong for its weight.",
    effect: "HP 6, Break DC 28, +4 to Use Rope checks, weighs 1/5 normal",
  },
  {
    id: "rare_scroll_protection_evil",
    name: "Scroll of Protection from Evil",
    category: "consumable",
    value: 50,
    weight: 0.1,
    description: "A divine scroll penned on vellum with silver ink.",
    effect: "Casts Protection from Evil (CL 1); +2 deflection AC and +2 resistance saves vs evil creatures for 1 min",
  },
  // A&E Guide trade goods — rare tier
  {
    id: "rare_sable_pelt",
    name: "Sable Pelt",
    category: "trade_good",
    value: 50,
    weight: 0.5,
    description: "A luxurious sable fur, dark and silky. Only nobility wears these.",
  },
  {
    id: "rare_tyrian_purple_dye",
    name: "Vial of Tyrian Purple",
    category: "trade_good",
    value: 150,
    weight: 0.5,
    description: "A tiny vial of murex-shell dye. The royal color — worth a fortune per ounce.",
  },
  {
    id: "rare_gold_bar_small",
    name: "Small Gold Bar",
    category: "trade_good",
    value: 50,
    weight: 1,
    description: "A one-pound bar of refined gold, stamped with a mint mark.",
  },
  {
    id: "rare_barrel_fine_wine",
    name: "Barrel of Fine Wine",
    category: "trade_good",
    value: 100,
    weight: 50,
    description: "A small cask of aged elven red, sealed with wax. A noble's vintage.",
  },
  {
    id: "rare_bale_exotic_furs",
    name: "Bale of Exotic Furs",
    category: "trade_good",
    value: 100,
    weight: 15,
    description: "A pressed bale of mixed furs — mink, ermine, and fox. Trade caravan staple.",
  },
  {
    id: "rare_chest_of_tea",
    name: "Chest of Fine Tea",
    category: "trade_good",
    value: 75,
    weight: 10,
    description: "A cedar chest packed with dried tea leaves from the eastern mountains.",
  },
  {
    id: "rare_silver_tea_service",
    name: "Silver Tea Service",
    category: "trade_good",
    value: 100,
    weight: 5,
    description: "A polished silver teapot with four cups and a tray. Finely engraved.",
  },
  {
    id: "rare_ivory_chess_set",
    name: "Ivory Chess Set",
    category: "trade_good",
    value: 80,
    weight: 3,
    description: "A chess set carved from walrus ivory and ebony. Each piece is a tiny masterwork.",
  },
  {
    id: "rare_crystal_decanter",
    name: "Crystal Decanter",
    category: "trade_good",
    value: 75,
    weight: 2,
    description: "A cut crystal decanter that throws rainbows in the light.",
  },
  {
    id: "rare_gold_holy_symbol",
    name: "Gold Holy Symbol",
    category: "gear",
    value: 100,
    weight: 1,
    description: "A holy symbol cast in solid gold, set with a tiny garnet.",
    effect: "Divine focus for spellcasting",
  },
  {
    id: "rare_masterwork_lute",
    name: "Masterwork Lute",
    category: "gear",
    value: 100,
    weight: 3,
    description: "A lute of rare rosewood and mother-of-pearl inlay. Resonant, beautiful tone.",
    effect: "+2 circumstance bonus to Perform (string) checks",
  },
  {
    id: "rare_riding_horse",
    name: "Riding Horse",
    category: "trade_good",
    value: 75,
    weight: 0,
    description: "A healthy, trained light horse suitable for riding. Comes with bridle.",
  },
  {
    id: "rare_guard_dog",
    name: "Trained Guard Dog",
    category: "trade_good",
    value: 25,
    weight: 0,
    description: "A large mastiff trained to guard and attack on command.",
  },
  {
    id: "rare_exotic_saddle",
    name: "Military Saddle",
    category: "gear",
    value: 60,
    weight: 30,
    description: "A reinforced war saddle with stirrups, cantle, and weapon hooks.",
    effect: "+2 circumstance bonus to Ride checks to stay in saddle",
  },
  {
    id: "rare_mw_thieves_tools",
    name: "Masterwork Thieves' Tools",
    category: "gear",
    value: 100,
    weight: 2,
    description: "Exquisitely crafted lockpicks of tempered steel in a velvet-lined case.",
    effect: "+2 circumstance bonus to Open Lock checks (stacks with skill)",
  },
  {
    id: "rare_spice_chest",
    name: "Chest of Mixed Spices",
    category: "trade_good",
    value: 120,
    weight: 10,
    description: "A merchant's sample chest: saffron, cloves, cardamom, star anise, and nutmeg.",
  },
  {
    id: "rare_bolt_of_velvet",
    name: "Bolt of Velvet",
    category: "trade_good",
    value: 80,
    weight: 5,
    description: "A roll of deep crimson velvet. Tailors and upholsterers will bid high.",
  },
  {
    id: "rare_silver_candlelabra",
    name: "Silver Candelabra",
    category: "trade_good",
    value: 90,
    weight: 4,
    description: "A three-armed silver candelabra with leaf-and-vine engravings.",
  },
  {
    id: "rare_potion_cats_grace",
    name: "Potion of Cat's Grace",
    category: "consumable",
    value: 150,
    weight: 0.5,
    description: "A swirling amber potion that smells of wild grass and ozone.",
    effect: "+4 enhancement bonus to DEX for 3 minutes",
  },
  {
    id: "rare_potion_bulls_strength",
    name: "Potion of Bull's Strength",
    category: "consumable",
    value: 150,
    weight: 0.5,
    description: "A thick red potion that tastes like iron and courage.",
    effect: "+4 enhancement bonus to STR for 3 minutes",
  },
];

// ============================================================
//  LEGENDARY LOOT  (150 – 500+ gp)
//  Masterwork weapons, exotic arms, high-value A&E trade goods
// ============================================================

export const LEGENDARY_LOOT: LootItem[] = [
  // Masterwork weapons (DMG/A&E)
  {
    id: "legend_mw_longsword",
    name: "Masterwork Longsword",
    category: "weapon",
    value: 315,
    weight: 4,
    description: "A flawlessly forged longsword with a mirror-bright blade and wire-wrapped grip. Forge-marked by a master smith.",
    effect: "1d8 slashing, 19-20/x2 crit; +1 attack (masterwork)",
  },
  {
    id: "legend_mw_greatsword",
    name: "Masterwork Greatsword",
    category: "weapon",
    value: 350,
    weight: 8,
    description: "A two-handed blade of impeccable steel, the fuller etched with a maker's rune.",
    effect: "2d6 slashing, 19-20/x2 crit; +1 attack (masterwork)",
  },
  {
    id: "legend_mw_greataxe",
    name: "Masterwork Greataxe",
    category: "weapon",
    value: 320,
    weight: 12,
    description: "A broad-headed war axe with twin crescent blades on a steel-capped haft.",
    effect: "1d12 slashing, x3 crit; +1 attack (masterwork)",
  },
  {
    id: "legend_mw_comp_longbow",
    name: "Masterwork Composite Longbow",
    category: "weapon",
    value: 400,
    weight: 3,
    description: "A recurve longbow of laminated horn and sinew, smooth as glass to draw.",
    effect: "1d8 piercing, x3 crit, 110 ft range; +1 attack (masterwork)",
  },
  {
    id: "legend_mw_heavy_crossbow",
    name: "Masterwork Heavy Crossbow",
    category: "weapon",
    value: 350,
    weight: 8,
    description: "A precision-machined heavy crossbow with a polished walnut stock and brass fittings.",
    effect: "1d10 piercing, 19-20/x2 crit, 120 ft range; +1 attack (masterwork)",
  },
  {
    id: "legend_mw_warhammer",
    name: "Masterwork Warhammer",
    category: "weapon",
    value: 312,
    weight: 5,
    description: "A dwarven-forged warhammer with a hardened steel head and octagonal grip.",
    effect: "1d8 bludgeoning, x3 crit; +1 attack (masterwork)",
  },
  {
    id: "legend_mw_rapier",
    name: "Masterwork Rapier",
    category: "weapon",
    value: 320,
    weight: 2,
    description: "A slender dueling blade with a swept hilt of chased silver.",
    effect: "1d6 piercing, 18-20/x2 crit; +1 attack (masterwork)",
  },
  // Exotic weapons (A&E)
  {
    id: "legend_bastard_sword",
    name: "Bastard Sword",
    category: "weapon",
    value: 35,
    weight: 6,
    description: "A hand-and-a-half sword usable one-handed by those with the training.",
    effect: "1d10 slashing, 19-20/x2 crit; exotic weapon proficiency required for one-handed use",
  },
  {
    id: "legend_dwarven_waraxe",
    name: "Dwarven Waraxe",
    category: "weapon",
    value: 30,
    weight: 8,
    description: "A broad-bladed axe balanced for one-handed dwarven fighting style.",
    effect: "1d10 slashing, x3 crit; exotic weapon proficiency for one-handed use",
  },
  {
    id: "legend_spiked_chain",
    name: "Spiked Chain",
    category: "weapon",
    value: 25,
    weight: 10,
    description: "A length of barbed chain whirled in deadly arcs. Requires unusual training.",
    effect: "2d4 piercing, x2 crit; reach, can trip; exotic weapon proficiency required",
  },
  // Masterwork armor
  {
    id: "legend_mw_chain_shirt",
    name: "Masterwork Chain Shirt",
    category: "armor",
    value: 250,
    weight: 25,
    description: "Finely riveted chain links polished to a soft gleam. Light and supple.",
    effect: "+4 AC, max Dex +4, armor check penalty -1 (masterwork)",
  },
  {
    id: "legend_mw_breastplate",
    name: "Masterwork Breastplate",
    category: "armor",
    value: 350,
    weight: 30,
    description: "A gleaming steel breastplate with fluted shoulders and articulated faulds.",
    effect: "+5 AC, max Dex +3, armor check penalty -3 (masterwork)",
  },
  {
    id: "legend_mw_studded_leather",
    name: "Masterwork Studded Leather",
    category: "armor",
    value: 175,
    weight: 20,
    description: "Studded leather armor of exceptional quality, supple yet tough.",
    effect: "+3 AC, max Dex +5, armor check penalty 0 (masterwork)",
  },
  {
    id: "legend_mw_scale_mail",
    name: "Masterwork Scale Mail",
    category: "armor",
    value: 200,
    weight: 30,
    description: "Overlapping steel scales, each one individually tempered and fitted.",
    effect: "+4 AC, max Dex +3, armor check penalty -3 (masterwork)",
  },
  {
    id: "legend_mw_heavy_steel_shield",
    name: "Masterwork Heavy Shield",
    category: "armor",
    value: 170,
    weight: 15,
    description: "A heavy steel shield with a mirror finish and reinforced boss.",
    effect: "+2 AC, armor check penalty -1 (masterwork)",
  },
  // High-value A&E trade goods (150-500gp)
  {
    id: "legend_gold_bar_large",
    name: "Gold Bar (5 lb)",
    category: "trade_good",
    value: 250,
    weight: 5,
    description: "Five pounds of refined gold in a single bar, stamped with a royal mint seal.",
  },
  {
    id: "legend_platinum_coin_pouch",
    name: "Pouch of Platinum Coins",
    category: "trade_good",
    value: 500,
    weight: 1,
    description: "A velvet drawstring pouch containing fifty platinum coins.",
  },
  {
    id: "legend_bolt_of_cloth_of_gold",
    name: "Bolt of Cloth-of-Gold",
    category: "trade_good",
    value: 300,
    weight: 6,
    description: "Fabric woven with real gold thread. Reserved for royalty and high clergy.",
  },
  {
    id: "legend_crate_of_tyrian_purple",
    name: "Crate of Tyrian Purple Dye",
    category: "trade_good",
    value: 450,
    weight: 15,
    description: "Three pounds of murex-shell dye in sealed clay jars. A merchant's fortune.",
  },
  {
    id: "legend_ivory_tusk",
    name: "Ivory Tusk",
    category: "trade_good",
    value: 200,
    weight: 10,
    description: "An elephant tusk, polished and cured. Carvers and artisans pay handsomely.",
  },
  {
    id: "legend_bale_of_sable",
    name: "Bale of Sable Furs",
    category: "trade_good",
    value: 350,
    weight: 8,
    description: "A dozen matched sable pelts, bundled and sealed. A noble's winter wardrobe.",
  },
  {
    id: "legend_amber_chunk",
    name: "Large Amber Specimen",
    category: "trade_good",
    value: 200,
    weight: 1,
    description: "A fist-sized piece of clear amber with an ancient insect perfectly preserved within.",
  },
  {
    id: "legend_spice_merchants_chest",
    name: "Spice Merchant's Locked Chest",
    category: "trade_good",
    value: 400,
    weight: 20,
    description: "An iron-bound cedar chest packed with saffron, vanilla, cloves, and star anise. A caravan's profit.",
  },
  {
    id: "legend_warhorse",
    name: "Light Warhorse",
    category: "trade_good",
    value: 150,
    weight: 0,
    description: "A trained light warhorse, battle-steady and armored with leather barding.",
  },
  {
    id: "legend_heavy_warhorse",
    name: "Heavy Warhorse",
    category: "trade_good",
    value: 400,
    weight: 0,
    description: "A massive destrier bred for war. Trained to charge, trample, and stand firm.",
  },
  {
    id: "legend_gold_chalice",
    name: "Gold Chalice",
    category: "trade_good",
    value: 200,
    weight: 2,
    description: "A solid gold chalice with ruby-set stem. Temple or noble house piece.",
  },
  {
    id: "legend_jeweled_dagger",
    name: "Jeweled Ceremonial Dagger",
    category: "weapon",
    value: 300,
    weight: 1,
    description: "A curved dagger with an emerald pommel and gold-inlaid blade. More art than weapon.",
    effect: "1d4 piercing, 19-20/x2 crit; worth double as art object",
  },
  {
    id: "legend_tapestry",
    name: "Large Wool Tapestry",
    category: "trade_good",
    value: 250,
    weight: 20,
    description: "A richly dyed tapestry depicting a famous battle, six feet tall and ten wide.",
  },
  {
    id: "legend_silver_dinner_set",
    name: "Silver Dinner Service",
    category: "trade_good",
    value: 300,
    weight: 15,
    description: "A complete 12-place silver dinner service in a felt-lined wooden chest.",
  },
  {
    id: "legend_darkwood_shield",
    name: "Darkwood Shield",
    category: "armor",
    value: 257,
    weight: 5,
    description: "A shield carved from darkwood — half the weight of steel with the same strength.",
    effect: "+2 AC, armor check penalty -1; weighs half normal (special material)",
  },
  // High-level consumables
  {
    id: "legend_potion_cure_moderate",
    name: "Potion of Cure Moderate Wounds",
    category: "consumable",
    value: 300,
    weight: 0.5,
    description: "A glowing red potion in a crystal phial, sealed with blessed wax.",
    effect: "Heals 2d8+3 hit points when consumed",
  },
  {
    id: "legend_potion_invisibility",
    name: "Potion of Invisibility",
    category: "consumable",
    value: 300,
    weight: 0.5,
    description: "A potion that refracts light through its glass, making your hand seem to vanish.",
    effect: "Invisible for 3 minutes or until you attack",
  },
  {
    id: "legend_potion_fly",
    name: "Potion of Fly",
    category: "consumable",
    value: 375,
    weight: 0.5,
    description: "A pale blue potion that fizzes and floats slightly in its bottle.",
    effect: "Fly 60 ft (good) for 5 minutes",
  },
  {
    id: "legend_scroll_fireball",
    name: "Scroll of Fireball",
    category: "consumable",
    value: 375,
    weight: 0.1,
    description: "An arcane scroll inscribed in fiery red ink that seems to flicker.",
    effect: "Casts Fireball (CL 5); 5d6 fire damage, 20 ft radius, DC 14 Reflex half",
  },
  {
    id: "legend_scroll_cure_serious",
    name: "Scroll of Cure Serious Wounds",
    category: "consumable",
    value: 375,
    weight: 0.1,
    description: "A divine scroll on blessed parchment, the words glowing faintly gold.",
    effect: "Casts Cure Serious Wounds (CL 5); heals 3d8+5 hit points",
  },
  // Alchemical high-value
  {
    id: "legend_sovereign_glue",
    name: "Sovereign Glue (1 oz)",
    category: "alchemical",
    value: 200,
    weight: 0.1,
    description: "A tiny vial of legendary adhesive. Bonds any two surfaces permanently.",
    effect: "Permanently bonds any two surfaces; only Universal Solvent can undo it",
  },
  {
    id: "legend_universal_solvent",
    name: "Universal Solvent (1 oz)",
    category: "alchemical",
    value: 200,
    weight: 0.1,
    description: "A shimmering liquid that dissolves any adhesive, including Sovereign Glue.",
    effect: "Dissolves any adhesive or binding on contact",
  },
];

// ============================================================
//  TERRAIN LOOT FLAVOR
// ============================================================

export const TERRAIN_LOOT: TerrainLoot[] = [
  {
    terrain: "farm",
    junk: [
      "You find a rusted horseshoe half-buried in the mud.",
      "An old scarecrow's hat lies trampled at the edge of the field.",
      "A broken fence post yields a handful of bent nails.",
      "You discover a cracked clay jug tucked behind a hay bale.",
      "A moth-eaten grain sack holds nothing but weevils and dust.",
    ],
    minor: [
      "Tucked in a barn wall niche, you find something wrapped in oilcloth.",
      "A farmhand's stash beneath a floorboard holds a few useful items.",
      "Behind the water trough, someone left a leather pouch.",
      "The root cellar holds more than turnips — there's gear hidden here.",
      "Hanging from a rafter, a forgotten satchel contains supplies.",
    ],
    major: [
      "Beneath the old oak tree, a buried strongbox holds the farmer's savings.",
      "In the hayloft, hidden under straw, you find a soldier's hidden cache.",
      "The stone well has a false bottom concealing a waterproof bundle.",
      "A hollow fence post contains something wrapped in fine leather.",
      "Behind a loose stone in the fireplace, a small fortune glints.",
    ],
  },
  {
    terrain: "forest",
    junk: [
      "A rotting log splits open to reveal some worthless curiosities.",
      "You spot something glinting in the leaf litter — just trash.",
      "A bird's nest holds shiny bits of scavenged debris.",
      "Tangled in old spider webs, you find some forgotten scraps.",
      "A hollow stump holds the moldering remains of someone's pack.",
    ],
    minor: [
      "A traveler's camp, long abandoned, still has a few useful items.",
      "Carved into a tree trunk is a small cache hidden by a ranger.",
      "A fox den entrance is littered with scavenged items, some still good.",
      "You find a leather satchel hanging from a high branch.",
      "Beneath a mossy rock, someone stashed supplies in a waxed bag.",
    ],
    major: [
      "An old hunter's blind conceals a well-preserved chest of valuables.",
      "The hollow of an ancient oak holds a poacher's secret stash.",
      "You discover a bandit's buried loot at the base of a lightning-split tree.",
      "A druid's offering stone holds gifts left by grateful villagers.",
      "Beneath a waterfall pool, something glitters among the smooth stones.",
    ],
  },
  {
    terrain: "plains",
    junk: [
      "Wind-scoured bones of some animal hold a few scraps caught in the ribs.",
      "A collapsed cairn yields nothing but rubble and a few trinkets.",
      "You find the wreckage of a wagon wheel with some bits still attached.",
      "A prairie dog mound has pushed up some buried refuse.",
      "Tall grass conceals a long-dead traveler's meager possessions.",
    ],
    minor: [
      "A half-buried saddlebag pokes up from the dirt after recent rains.",
      "A merchant's milestone has a hollow compartment in its base.",
      "You find an overturned cart with a few salvageable goods.",
      "A shepherd's abandoned lean-to still holds some useful supplies.",
      "The remains of a campfire ring hide a buried cache beneath the ashes.",
    ],
    major: [
      "A collapsed barrow mound reveals grave goods spilling from the earth.",
      "An old battlefield yields a fallen knight's possessions.",
      "A lightning strike has unearthed a buried chest from some past age.",
      "You discover a smuggler's drop point marked by three stacked stones.",
      "Beneath a lone standing stone, a ritual offering cache lies undisturbed.",
    ],
  },
  {
    terrain: "road",
    junk: [
      "The roadside ditch holds the usual debris of passing caravans.",
      "A milestone's base is cluttered with discarded odds and ends.",
      "You kick something in the dust — just road-worn junk.",
      "A collapsed signpost has some worthless bits tangled at its base.",
      "The ruts in the road have trapped a few small objects in dried mud.",
    ],
    minor: [
      "A traveler's dropped pack lies just off the road, still partly stocked.",
      "Behind a roadside shrine, someone left a thank-offering.",
      "A peddler's broken cart still has a few intact goods in the wreckage.",
      "You find a courier's lost satchel wedged between roadside boulders.",
      "An overturned wagon reveals goods that rolled beneath the chassis.",
    ],
    major: [
      "A bandit ambush site holds the robbers' own stashed loot nearby.",
      "Beneath a bridge, a smuggler's cache is wedged between the stones.",
      "An abandoned toll booth has a locked strongbox still bolted down.",
      "The ruins of a roadside inn conceal a hidden compartment in the floor.",
      "A merchant's buried emergency fund, marked by a carved stone, awaits.",
    ],
  },
  {
    terrain: "town",
    junk: [
      "The alley behind the tavern is littered with the usual refuse.",
      "A gutter drain has accumulated some small worthless objects.",
      "You spot something in a refuse pile — barely worth picking up.",
      "An abandoned market stall still has a few forgotten scraps.",
      "The town well's edge is crusted with lost coins too corroded to spend.",
    ],
    minor: [
      "A loose cobblestone hides a thief's small cache.",
      "Behind a tavern barrel, you find a pouch someone hid and forgot.",
      "An abandoned basement holds a few items left by former tenants.",
      "A hollowed-out book on a junk seller's shelf holds more than pages.",
      "The rafters of an old stable conceal a wrapped bundle.",
    ],
    major: [
      "A secret compartment in a condemned building yields hidden wealth.",
      "Beneath a statue in the town square, a time-worn vault lies unsealed.",
      "An old merchant's wall safe, forgotten during renovations, still holds treasure.",
      "The temple donation box has an overlooked false bottom.",
      "A noble's abandoned townhouse has a hidden panel behind the hearth.",
    ],
  },
  {
    terrain: "swamp",
    junk: [
      "The muck yields something when you step on it — just soggy trash.",
      "A half-sunken log is wrapped in rotting fabric holding a few scraps.",
      "Bubbles rising from the mud reveal a pocket of buried refuse.",
      "A dead tree's roots grip some waterlogged junk.",
      "You pull something from the peat — worthless but interesting.",
    ],
    minor: [
      "A will-o'-wisp led some poor soul here; their pack is still intact.",
      "A poacher's elevated cache box is nailed to a cypress trunk.",
      "The remains of a flat-bottomed boat hold a few salvageable items.",
      "A lizardfolk offering mound contains items of human make.",
      "Wrapped in oiled leather atop a hummock, a small stash survives the damp.",
    ],
    major: [
      "A sunken shrine rises from the water at low tide, its offerings gleaming.",
      "The bog preserves everything — including a merchant's locked coffer.",
      "A witch's abandoned hut holds alchemical supplies and hidden valuables.",
      "Deep in the swamp, a bandit hideout still contains their accumulated loot.",
      "You discover a petrified tree with a cavity stuffed full of treasure.",
    ],
  },
  {
    terrain: "mountain",
    junk: [
      "A rockslide has exposed some buried refuse from a collapsed camp.",
      "A mountain goat trail passes by a cairn holding a few worthless bits.",
      "Wind has swept some debris into a rocky crevice.",
      "You find the frozen remains of a shattered pack, contents mostly ruined.",
      "A shallow cave mouth is littered with bone scraps and cast-off junk.",
    ],
    minor: [
      "A climber's piton trail leads to an abandoned cache on a ledge.",
      "A mountain hermit's shelter holds some useful supplies and gear.",
      "An eagle's nest on a reachable outcrop contains scavenged items.",
      "A mine entrance has a few discarded tools and supplies still usable.",
      "A crevice in the rock face conceals a traveler's emergency stash.",
    ],
    major: [
      "A dwarven waystone has a concealed compartment holding clan treasures.",
      "An avalanche reveals a long-buried prospector's camp with his finds.",
      "A dragon's old minor lair holds a scattering of coins and a few prizes.",
      "High on a peak, a shrine to a mountain god holds precious offerings.",
      "A collapsed mine tunnel opens to reveal a vein of ore and cached valuables.",
    ],
  },
  {
    terrain: "desert",
    junk: [
      "The wind has scoured the sand away from some bleached and worthless debris.",
      "A dried-out waterskin and some sun-cracked belongings litter the dunes.",
      "Sand partially buries the remnants of a long-dead traveler's meager goods.",
      "You find a scorpion nest built around some discarded trinkets.",
      "A sand drift has swallowed most of a camp, leaving only scraps.",
    ],
    minor: [
      "An oasis cache, marked by stacked stones, holds supplies for travelers.",
      "A sand storm has uncovered a buried saddlebag still partly intact.",
      "A nomad's abandoned tent holds a few trade goods and tools.",
      "The base of a desert pillar has a hollow compartment with supplies.",
      "A vulture circles over a lost caravan — some cargo is still salvageable.",
    ],
    major: [
      "Shifting sands reveal the top of a buried tomb, its seals partially broken.",
      "A sandstorm exposes an ancient trader's cache, sealed in clay jars.",
      "An abandoned desert fortress has a treasury room, mostly looted but not empty.",
      "A rare flash flood washes treasure down from the hidden highlands.",
      "Beneath a fallen obelisk, a pharaoh's offering cache lies undisturbed.",
    ],
  },
  {
    terrain: "water",
    junk: [
      "The riverbed holds some waterlogged junk caught between stones.",
      "A tangle of flotsam has accumulated against the bank.",
      "You spot something on the bottom — just rusted and worthless debris.",
      "A fish trap, long abandoned, holds some soggy refuse.",
      "The tide has deposited a line of wrack with a few sad objects.",
    ],
    minor: [
      "A shipwreck's debris field has washed ashore with some intact cargo.",
      "A fisherman's sunken boat is shallow enough to reach, cargo partly dry.",
      "Behind a waterfall, a shallow cave holds a traveler's dry-stored goods.",
      "A river trader's lost crate bobs in an eddy, still sealed.",
      "Oyster beds near the shore yield a few shells worth checking.",
    ],
    major: [
      "A sunken chest, visible through clear water, can be reached with effort.",
      "A sea cave at low tide reveals a smuggler's hidden stores.",
      "The wreck of a merchant vessel has spilled its cargo across the shallows.",
      "A lake shrine, half-submerged, holds offerings from generations of pilgrims.",
      "A river spirit's grotto glitters with gifts left by superstitious travelers.",
    ],
  },
  {
    terrain: "underground",
    junk: [
      "A collapsed section of tunnel reveals some ancient, worthless debris.",
      "Fungus-covered bones hold a few corroded personal effects.",
      "A stagnant pool has accumulated some mineral-crusted junk.",
      "A rat warren is built from scavenged trash and small shiny objects.",
      "Old mine timbers have pinned some useless scraps against the wall.",
    ],
    minor: [
      "A dead adventurer's pack, partly eaten by ooze, still holds some gear.",
      "A kobold's stash behind loose stones contains pilfered supplies.",
      "An underground stream has deposited items in a natural catch basin.",
      "A worked-stone niche in the tunnel wall holds a deliberate cache.",
      "A spider's web-wrapped bundle turns out to be a lost traveler's satchel.",
    ],
    major: [
      "A sealed stone coffer behind a false wall holds dungeon builders' pay.",
      "An underground temple's offering bowl still holds precious gifts.",
      "A dragon's secondary hoard room — just scraps by dragon standards — is a fortune to you.",
      "A deepkin trader's hidden vault is concealed behind an illusion that has faded.",
      "A geode cavern glitters with crystals, some of which are genuine gemstones.",
    ],
  },
];

// ============================================================
//  HELPER FUNCTIONS
// ============================================================

/**
 * Pick a random item from the given loot tier.
 */
export function pickLoot(tier: LootTier): LootItem {
  const table = getLootTable(tier);
  return table[Math.floor(Math.random() * table.length)];
}

/**
 * Roll a loot drop based on character level range and find outcome.
 *
 * Level 1-2:   minor → junk/common       major → common/uncommon
 * Level 3-5:   minor → common/uncommon    major → uncommon/rare
 * Level 6-8:   minor → uncommon/rare      major → rare/legendary
 * Level 9-12:  minor → rare/legendary     major → legendary + legendary
 * Level 13+:   minor → legendary          major → 2 legendary
 */
export function rollLootDrop(
  levelRange: [number, number],
  outcome: "minor_find" | "major_find"
): LootItem[] {
  const avgLevel = (levelRange[0] + levelRange[1]) / 2;

  if (outcome === "minor_find") {
    if (avgLevel >= 13) return [pickLoot("legendary")];
    if (avgLevel >= 9)  return coinFlip() ? [pickLoot("legendary")] : [pickLoot("rare"), pickLoot("rare")];
    if (avgLevel >= 6)  return coinFlip() ? [pickLoot("rare")] : [pickLoot("uncommon"), pickLoot("uncommon")];
    if (avgLevel >= 3)  return coinFlip() ? [pickLoot("uncommon")] : [pickLoot("common"), pickLoot("common")];
    return coinFlip() ? [pickLoot("common")] : [pickLoot("junk"), pickLoot("junk")];
  } else {
    // major_find
    if (avgLevel >= 13) return [pickLoot("legendary"), pickLoot("legendary")];
    if (avgLevel >= 9)  return coinFlip() ? [pickLoot("legendary"), pickLoot("rare")] : [pickLoot("legendary")];
    if (avgLevel >= 6)  return coinFlip() ? [pickLoot("legendary")] : [pickLoot("rare"), pickLoot("rare")];
    if (avgLevel >= 3)  return coinFlip() ? [pickLoot("rare")] : [pickLoot("uncommon"), pickLoot("uncommon")];
    return coinFlip() ? [pickLoot("uncommon")] : [pickLoot("common"), pickLoot("common")];
  }
}

/**
 * Get a random terrain-specific flavor text for a loot discovery.
 */
export function getTerrainLootFlavor(
  terrain: string,
  tier: "junk" | "minor" | "major"
): string {
  const entry = TERRAIN_LOOT.find(
    (t) => t.terrain.toLowerCase() === terrain.toLowerCase()
  );
  if (!entry) {
    // Fallback for unknown terrain
    const fallbacks = {
      junk: "You find some scattered debris.",
      minor: "You discover a small cache of useful items.",
      major: "You uncover a well-hidden stash of valuables.",
    };
    return fallbacks[tier];
  }

  const pool = entry[tier];
  return pool[Math.floor(Math.random() * pool.length)];
}

// ============================================================
//  INTERNAL UTILITIES
// ============================================================

function getLootTable(tier: LootTier): LootItem[] {
  switch (tier) {
    case "junk":
      return JUNK_LOOT;
    case "common":
      return COMMON_LOOT;
    case "uncommon":
      return UNCOMMON_LOOT;
    case "rare":
      return RARE_LOOT;
    case "legendary":
      return LEGENDARY_LOOT;
  }
}

/** Look up a loot item by ID across all tiers */
const ALL_LOOT = [...JUNK_LOOT, ...COMMON_LOOT, ...UNCOMMON_LOOT, ...RARE_LOOT, ...LEGENDARY_LOOT];
const LOOT_MAP = new Map(ALL_LOOT.map(i => [i.id, i]));
export function getItemById(id: string): LootItem | undefined {
  return LOOT_MAP.get(id);
}

function coinFlip(): boolean {
  return Math.random() < 0.5;
}
